export const LOAD_DATA_REQUEST = "LOAD_DATA_REQUEST";
export const LOAD_DATA_REQUEST_REPOS = "LOAD_DATA_REQUEST_REPOS";
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
export const REMOVE_USER = 'REMOVE_USER';